### PR TITLE
fix: Support extracting generic bound from TypeVar

### LINKED ISSUE #87: Support Pydantic schemas with generic currency
Minimal reproduction:

```python
class A(
    SQLModel,
    Generic[C],
    table=True,
):
    value: Money[C]
```

Fails with:

```
[...]
  File "/Users/anton/.pyenv/versions/shop/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 616, in _generate_schema_from_property
    schema = get_schema(
             ^^^^^^^^^^^
  File "/Users/anton/.pyenv/versions/shop/lib/python3.12/site-packages/immoney/_base.py", line 445, in __get_pydantic_core_schema__
    return build_generic_currency_schema(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anton/.pyenv/versions/shop/lib/python3.12/site-packages/immoney/_pydantic.py", line 323, in build_generic_currency_schema
    currency_type = extract_currency_type_arg(source_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anton/.pyenv/versions/shop/lib/python3.12/site-packages/immoney/_pydantic.py", line 47, in extract_currency_type_arg
    raise TypeError(f"Invalid type args: {invalid!r}.")
TypeError: Invalid type args: (~C,).
```

### PR DESCRIPTION
**Pull request by antonagestam**
Adds support for Pydantic models that are generic with a currency type.

Fixes #87.

### CODE REVIEW

**Comment by zvsdev** [comment]
@antonagestam I've been trying this branch out locally on a project so far it's working great. What kinds of tests did you want to add for it?

**Comment by antonagestam** [comment]
> @antonagestam I've been trying this branch out locally on a project so far it's working great. What kinds of tests did you want to add for it?

Hey there, I'm happy to hear this is working out for you. This was a long time ago, but it looks like the new conditionals need to be covered, and the TypeError case might have also changed.

**Comment by antonagestam** [comment]
@zvsdev as long as there's some unit test covering the three exit possibilities of this function, I'd be happy. In case you're willing to work on this, please feel entirely free to modify and push this work as your own in a new PR!

**Comment by antonagestam** [comment]
@zvsdev I just merged this, thanks for the friendly nudge! It's released now in version 0.10.0.

**Comment by zvsdev** [comment]
@antonagestam aha awesome speed! BTW amazing work on this package, won't be long before pydantic takes over the fintech world.

**Pull request merged**
